WIP Add sixth mojolicious
perl-entrance-org/workshop-basic-online pull request #110
Opened 2023-01-24 23:30 UTC by tomcha

第６回として、過去のMojolicious回を移植作業中です。
主な変更点は、コマンドで生成されるアプリ雛形でのコントローラー受け渡し部分の変更です。
シグネチャ？あたりの説明が技術的に合っているか見てもらえれば助かります。

2023-02-08 14:24 UTC, xtetsuji commented
オンラインミーティングで @sironekotoro さんとレビュー予定タスクとして押さえてあります。

以前の Mojolicious カリキュラムをコピーした 9559eb9 を除いた、次の修正コミット b38d684 から直前の修正コミット 550dd77 までの b38d684...550dd77 を見たほうが良いかなと思いました。このプルリクにレビューコメントをつけるには単なるコミット列挙 b38d684...550dd77 ではなく、以下のリンク

- https://github.com/perl-entrance-org/workshop-basic-online/pull/110/files/9559eb93e93132f715e4715f1aadda4ef0e82413..63d7d9acfd2761c531d2aefdbeebe16cdacea388

からこのプルリクに対してのレビューコメントを付けられる……とメモ。

詳細レビューは今週末あたり予定です。

2023-02-08 14:43 UTC, sironekotoro commented
>第1回目で Term::ANSIColor モジュールを使いましたが、それは全ての Perl に最初から入っているモジュールでした。

今回の編集範囲ではないですが、現行の第1回では Term::ANSIColor は利用していないので、28行目の上記の一文は削除でよさそうです。

2023-02-08 15:22 UTC, sironekotoro commented
@tomcha @xtetsuji 
47行目以降のモジュールをインストールするコマンドのところ
```
$ curl -L cpanmin.us -o cpanm
$ chmod +x cpanm
$ ./cpanm -l ~/extlib local::lib
$ perl -I ~/extlib/lib/perl5 -Mlocal::lib=~/extlib | tee -a ~/.bash_profile
$ exec $SHELL -l
$ ./cpanm -n Mojolicious
```

以下の行は bash 前提だから、今のMacだと `~/.bash_profile` を `~/.zshrc` に置き換える必要がありそう 
```
$ perl -I ~/extlib/lib/perl5 -Mlocal::lib=~/extlib | tee -a ~/.bash_profile
```

あと、以下の行を実行しても、インストール先の指定がないので `~/extlib` に Mojolicious が入らない？
今まで特にクレームも来なかったけど・・・
> ./cpanm -n Mojolicious

インストール先を指定したこれならいけると思うけど、手元の自分の環境だけなので不安。
> ./cpanm -l ~/extlib -n Mojolicious

2023-02-08 15:27 UTC, sironekotoro commented
@tomcha 
編集範囲じゃないところばかりですみません。
123行目
> Web ブラウザで ``http://127.0.0.1:3000`` にアクセスしてみましょう。

ここなのですが、ターミナルでは mojo が立ち上がったままなので、 `ctrl + z` または `ctrl + c` による終了の記載があるとよさそう。

2023-02-08 15:58 UTC, sironekotoro reviewed
サブルーチンシグネチャの説明は大丈夫だと思いました。

2023-02-08 15:58 UTC, sironekotoro commented on 6th/slide.md
> +- ``<h1> ... </h1>`` は見出しを表すのHTMLタグです。そのままHTMLとして表示されます。
>``<h1> ... </h1>`` は見出しを表すのHTMLタグです。
これは
>``<h1> ... </h1>`` は見出しを表すHTMLタグです。
でしょうかね。

2023-02-08 15:58 UTC, sironekotoro commented on 6th/slide.md
> +- つまり、``use Mojolicious::Lite -signatures;``を書くだけで、ついでに上記のように書いているのと同じということです。
> つまり、``use Mojolicious::Lite -signatures;``を書くだけで、ついでに上記のように書いているのと同じということです。

元の文にあった「ついで」ですが、なくても良さそうです。

2023-02-08 15:58 UTC, sironekotoro commented on 6th/slide.md
> +use Mojolicious::Lite -signatures;
サブルーチンシグネチャ！？と思ったら、公式がそれを推奨していたんですね。
https://docs.mojolicious.org/Mojolicious/Lite

2023-02-08 15:58 UTC, sironekotoro commented on 6th/slide.md
>  - 一つ目の引数が``'/'``という文字列、二つ目の引数がコードリファレンスです。
「コードリファレンス」を含むところなのですが、
- 初出かつ、ここでしか出てこない語
- この先しばらく説明されることがなさそう
- ここだけ見れば、サブルーチンと全く同じ

なので、
```
一つ目の引数が``'/'``という文字列、二つ目の引数がコードリファレンスです。
（中略）
コードリファレンス ``sub () { ... }`` 部分では、先程紹介したシグネチャ機能により、サブルーチンの引数を ``()`` の中であらかじめ宣言することが可能です。
```
を
```
一つ目の引数が``'/'``という文字列、二つ目の引数が``sub () { ... }``です。
（中略）
``sub () { ... }`` 部分では、先程紹介したシグネチャ機能により、サブルーチンの引数を ``()`` の中であらかじめ宣言することが可能です。
```
とするのはどうでしょう？

180行目の「コードリファレンス」も削除しても意味は通じるので消してしまって大丈夫だと思います
>コードリファレンスの最初の行は、フレームワークのコントローラーを受け取っています。

2023-02-08 15:58 UTC, sironekotoro commented on 6th/slide.md
> +- コードリファレンス ``sub () { ... }`` 部分では、先程紹介したシグネチャ機能により、サブルーチンの引数を ``()`` の中であらかじめ宣言することが可能です。
シグネチャの説明は大丈夫だと思います。

2023-02-08 16:04 UTC, sironekotoro approved these changes

2023-02-12 17:10 UTC, xtetsuji requested changes
@tomcha 修正ありがとうございます！

日本語表記や細かい記載については @sironekotoro さんに見ていただいたので、私はサブルーチンシグネチャまわりをレビューしました。

**結論として、サブルーチンシグネチャの取り入れについて、概ね賛成です**。なにせ私がここ数年個人で書くスクリプトはサブルーチンシグネチャを普通にバンバン使っていて特に問題無いくらいなのと、Perl 5.36 で実験的ステータスを抜けたことが大きいです。

とはいえコメントの通り Perl 5.20 以上が必要な点について大半の受講生環境で問題がないかなど検討したいところですが、今期大阪が大丈夫であればマージした上で、2023年度が始まるまでにサポートが継続している OS に標準搭載されている Perl を調査したいと考えています。

今回のことをきっかけに、「モダンなPerlを教える」ことを標榜している Perl入学式が未だ Perl 5.8 の範囲にとどまっていることについて、サポーターミーティングでも話し合ったりしていました。Perl 5.36 はさすがに攻め過ぎ（macOS Ventura のシステム Perl も 5.30 なので……）としても、9年前の Perl 5.20 ならわりかしアリかなと。軽く調べましたが、Perl 5.22 以降の feature で Perl入学式ベーシック版に特段関係する部分は無さそう。

あと、Mojolicious のところでサブルーチンシグネチャを取り入れるのであれば、そもそも第3回か第4回のサブルーチンを教えるところでサブルーチンシグネチャを教えたいと考えています。個人的には受講生の混乱がないよう、両方の箇所で教えるか、両方の箇所で教えないのどちらかに統一したいです。サブルーチンシグネチャを教える場合、過去のコードを読むためにコラムとして `@_` の扱いに触れるなどの対応を検討しています。

2023-02-12 17:10 UTC, xtetsuji commented on 6th/slide.md
> +use fearuture 'signatures';
タイプミス修正。ついでに Perl 5.32 までは `use feature qw(signatures)` で警告が出るので、それの抑制のため `experimental` プラグマを追加。

```suggestion
use feature 'signatures';
use experimental 'signatures';
```

2023-02-12 17:10 UTC, xtetsuji commented on 6th/slide.md
> +use feature ':5.16';
この記述だと雰囲気で「Perl 5.16 以上で使えるんだ」と受講生や（この資料を使う）講師もミスリードされそうな気もしています（資料を一読した私がそうだったので……）。実際はこの下に書かれている `use feature qw(signatures)` またはそれを内部的に呼び出している `use Mojolicious::Lite -signatures` によって **Perl 5.20 以上が必要** となります（[コード参照](https://github.com/mojolicious/mojo/blob/03d1b64c2868da64f3a9d06a59ac83d1bee44f04/lib/Mojo/Base.pm#L124-L129)）。

もともと Perl 5.10 以上が必要であることの記載が無かったのですが、Perl 5.20 はほんの少しだけ攻めたバージョンであることと、ミスリードされやすいことから、軽く必要要件の最低バージョンの記載はしておいたほうが良いかなと思いました。

サブルーチンシグネチャの資料採用の是非そのものについては大本のコメントに記載しました。

2023-02-12 17:25 UTC, xtetsuji commented
@sironekotoro さんの https://github.com/perl-entrance-org/workshop-basic-online/pull/110#issuecomment-1422768078 より

> 以下の行は bash 前提だから、今のMacだと `~/.bash_profile` を `~/.zshrc` に置き換える必要がありそう
> 
> ```
> $ perl -I ~/extlib/lib/perl5 -Mlocal::lib=~/extlib | tee -a ~/.bash_profile
> ```

bash or zsh については、まず `echo $SHELL` を打ってもらって、その表示によって作業内容を分岐させたほうが良いかもと考えていました。ワンライナーで if 文書いて……とか考えたけれど、コピペが複雑にならない方がいいなぁと。

あと bash の `~/.bash_profile` に対応する zsh のファイルは `~/.zprofile` じゃなかったでしたっけ。zsh 力が弱くて断言できない……。[ytnobody/plenvsetup](https://github.com/ytnobody/plenvsetup/) でやっていることが参考になりそう。

最近知ったこととして、この `$SHELL` は現在のシェルではなくてログインシェルのことらしい（参考：[シェルスクリプトの中で現在利用しているシェルを確認する方法 - Qiita](https://qiita.com/akase244/items/c3040b68b5e08057c861)）のですが、この辺りを考えると色々ややこしそう。（自分で言っといてではありますが）今回は考えなくて良さそう。

> ```
> $ curl -L cpanmin.us -o cpanm
> $ chmod +x cpanm
> $ ./cpanm -l ~/extlib local::lib
> $ perl -I ~/extlib/lib/perl5 -Mlocal::lib=~/extlib | tee -a ~/.bash_profile
> $ exec $SHELL -l
> $ ./cpanm -n Mojolicious
> ```
> 
> 
> あと、以下の行を実行しても、インストール先の指定がないので `~/extlib` に Mojolicious が入らない？ 今まで特にクレームも来なかったけど・・・
> 
> > ./cpanm -n Mojolicious

ちょっとここ追試したいですね。2019年までは無意識にサポーターがフォローしていたのか、cpanm の挙動が変わったのか、何かありそう。

2023-02-26 06:57 UTC, tomcha commented on 6th/slide.md
> +use feature ':5.16';
ここと一つ上のコメントの件、このスライドでは
"mojo/Base.pmの先頭（3〜6行目）のプラグマ宣言が自動で有効になりますよ"
という解説箇所かと思いますが、どう書くのが分かりやすいか要相談です。
ただ、指摘のとおりgenerateしたLite-appではuse Mojolicious::Lite -signaturesと書かれているので、5.20以上必要になりそうです。（mojo/Base.pmのソースにもそうコメントしてますね）

これ、仮にPerl5.18のマシンでgenarateしたらどうなるんだろう？
コードは生成されるが、エラーが出るのかな？
（素朴な疑問）

2023-03-26 07:49 UTC, xtetsuji commented on 6th/slide.md
> +use feature ':5.16';
> これ、仮にPerl5.18のマシンでgenarateしたらどうなるんだろう？
> コードは生成されるが、エラーが出るのかな？

について、3月25日のオンラインミーティングでも話に上がりましたが、たぶん

- generate はできる
- 実行時に `use Mojo::Base -signatures;` に出会うと Perl 5.20 未満ではエラー（`feature` に怒られる）

かなと思います。

2023-04-05 06:04 UTC, xtetsuji commented on 6th/slide.md
> +use fearuture 'signatures';
4a9a624 で解決済み。

2023-04-05 06:04 UTC, xtetsuji commented on 6th/slide.md
> +- つまり、``use Mojolicious::Lite -signatures;``を書くだけで、ついでに上記のように書いているのと同じということです。
cc15c78 で解決済み。

2023-04-05 06:05 UTC, xtetsuji commented on 6th/slide.md
> +- ``<h1> ... </h1>`` は見出しを表すのHTMLタグです。そのままHTMLとして表示されます。
cc15c78 で解決済み。

2023-04-05 06:07 UTC, xtetsuji commented on 6th/slide.md
> +use feature ':5.16';
9e45b6c で解決済み。

2023-04-16 03:50 UTC, xtetsuji requested changes
@tomcha 修正ありがとうございます！追加修正部分でも typo があった以外はだいぶ大丈夫そうです。

zsh まわり、わからないところが若干あったので、いったん現状の資料ベースで大阪開催してもらって、そこで得られたフィードバックをもとに2023年度に向けて資料改訂していければと思いました！

2023-04-16 03:50 UTC, xtetsuji commented on 6th/slide.md
> +/usr/local/bin/zsh
これはたぶん Homebrew でインストールした zsh かな……。macOS に最初から入っている zsh は /bin/zsh のはず。

できれば /bin/zsh にしておいたほうがいいかなと思いました。

2023-04-16 03:50 UTC, xtetsuji commented on 6th/slide.md
> +$ perl -I ~/extlib/lib/perl5 -Mlocal::lib=~/extlib | tee -a ~/.bash_profilet
```suggestion
$ perl -I ~/extlib/lib/perl5 -Mlocal::lib=~/extlib | tee -a ~/.bash_profile
```

2023-04-16 03:50 UTC, xtetsuji commented on 6th/slide.md
> +$ perl -I ~/extlib/lib/perl5 -Mlocal::lib=~/extlib | tee -a ~/.zshrc
この部分、.zprofile と .zshrc のどちらが適切か分からなかったので、引き続き https://github.com/perl-entrance-org/workshop-basic-online/issues/111 で議論できたらと思いっています。

2023-04-16 03:50 UTC, xtetsuji commented on 6th/slide.md
> +- ただし一点注意が必要で、このコードはPerlのバージョン5.16までの新機能が使える様になるおまじない（プラグマ）ですが、 ``use fearure 'signatures' `` を実行するには、Perl5.20以上のバージョンが必要となります。
```suggestion
- ただし一点注意が必要で、このコードはPerlのバージョン5.16までの新機能が使える様になるおまじない（プラグマ）ですが、 ``use feature 'signatures' `` を実行するには、Perl5.20以上のバージョンが必要となります。
```

2023-04-16 23:11 UTC, tomcha commented on 6th/slide.md
> +/usr/local/bin/zsh
/bin/zsh へ変更しました。

2023-04-16 23:11 UTC, tomcha commented on 6th/slide.md
> +$ perl -I ~/extlib/lib/perl5 -Mlocal::lib=~/extlib | tee -a ~/.bash_profilet
typo修正しました。

2023-04-16 23:11 UTC, tomcha commented on 6th/slide.md
> +- ただし一点注意が必要で、このコードはPerlのバージョン5.16までの新機能が使える様になるおまじない（プラグマ）ですが、 ``use fearure 'signatures' `` を実行するには、Perl5.20以上のバージョンが必要となります。
typo修正しました。

2023-04-16 23:13 UTC, tomcha commented on 6th/slide.md
> +- ただし一点注意が必要で、このコードはPerlのバージョン5.16までの新機能が使える様になるおまじない（プラグマ）ですが、 ``use fearure 'signatures' `` を実行するには、Perl5.20以上のバージョンが必要となります。
レビュー、ありがとうございました。
修正箇所を直しましたので、レビュー、マージよろしくお願いいたします。

2023-04-17 04:04 UTC, xtetsuji approved these changes
@tomcha 修正ありがとうございます！マージします。

今回大阪でこの資料をもとに Mojolicious を講義した際にかかった時間を元に、2023年度の講義計画を立てられればと考えています。

2023-04-17 04:04 UTC, merged