add Chained comparisons capability
perl-entrance-org/workshop-basic-online pull request #12
Opened 2020-06-17 13:35 UTC by sironekotoro

- Perl 5.32 から導入される Chained comparisons capability によって例示コードの動作が変わるので対応
- https://metacpan.org/pod/release/XSAWYERX/perl-5.32.0-RC0/pod/perldelta.pod#Chained-comparisons-capability

2020-06-17 15:49 UTC, xtetsuji requested changes
@sironekotoro 修正ありがとうございます。

いちおう[Perl 5.32 の perlop](https://metacpan.org/pod/release/XSAWYERX/perl-5.32.0-RC1/pod/perlop.pod) にも目を通してみましたが、この部分に関する注意点はありませんでした。

perlop が言及していたのは、 `expensive_sub()` 評価が最大で2回発生する可能性がある

```pl
if($x < expensive_sub() && expensive_sub() <= $z) { ...
```

は（その複数回の副作用が重要な場合）

```pl
if($x < expensive_sub() <= $z) { ...
```

と等価ではないよということでした。というか Perl 5.30 までで、この最大2回 `expensive_sub()` の評価が発生することを意図して書くケースの方を知りたいくらい。

@tomcha 他に気になる点ありますでしょうか？

2020-06-17 15:49 UTC, xtetsuji commented on 2nd/slide.md
> +if ( $small < $medium < $large ) { # Perl 5.30ではエラーになる
我々は勘違いしないですが、初学者は「私の Perl 5.28 は大丈夫」と思うかもしれないので、Perl 5.30 **までのバージョン** では……と書いてあげたほうがいいかもしれません。

2020-06-21 12:26 UTC, tomcha commented
お疲れ様です。簡潔で特に問題ないと思います！

2020-06-22 05:25 UTC, xtetsuji requested changes
Approve しようと思って最後にざっとみたところ、当初のレビューで見逃していた部分があったので追記しました。

私も前後のスライドを想定した上での良い修正が思いつかなかったので、いったん間違った記述だけを削除してマージでもいいかなと思います。後々良いアイデアが出たら、都度 Pull Request でいきましょう！

2020-06-22 05:25 UTC, xtetsuji commented on 2nd/slide.md
> +ただし、2020年にリリースされた Perl 5.32 より、3つ以上の値を同時に比較することが可能になりました。
本日無事に Perl 5.32 リリースされました。

- https://twitter.com/metacpan/status/1274738418623361028

なので「リリースされた」と過去形でも大丈夫！

2020-06-22 05:25 UTC, xtetsuji commented on 2nd/slide.md
> +```
おっと、ここ見逃していました 💦 

`<` `>` `<=` `>=` `lt` `gt` `le` `ge` について、優先順位は（異なるのではなく）同じです。

例えば、二項演算子で同じ優先順位のものが連続すると、例えばメジャーな左結合であれば `2 - 3 - 4 - 5` は `((2 - 3) - 4) - 5` となり、マイナーな右結合であれば `2 ** 3 ** 4 ** 5` は `2 ** (3 ** (4 ** 5))` となります。

上記不等号のグループでは、左結合でも右結合でもなく非結合 (noassoc) と perlop で書かれており、「これらの同じ優先順位のグループに属する二項演算子が連続して使われることはない（今まではなかった）」ということを言っていると私は理解しています。

‥…と思ったら [Perl 5.32 の perlop](https://metacpan.org/pod/release/XSAWYERX/perl-5.32.0/pod/perlop.pod) では

```
（前略）
left        << >>
nonassoc    named unary operators
chained     < > <= >= lt gt le ge
chain/na    == != eq ne <=> cmp ~~
nonassoc    isa
（後略）
```

と chained という扱いになっていますね。

優先順位のことには触れず、今までの書き方を提示したほうがいいかな。とはいえ、そうしたら次のスライドでほぼ同じことを重複して解説することになり、ちょっと悩みますね。とはいえ、Perl入学式の受講生に対しては間違った記述を回避しつつふわっとした解説で良いかなと感じています。

良い修正案が出なければ、いったん「優先順位が異なる」くだりを削除した上でマージして、週末のミーティング等でいいアイデアが出たら書き換えることにしましょうか。

2020-06-22 05:25 UTC, xtetsuji commented on 2nd/slide.md
> +if ( $small < $medium < $large ) { # Perl 5.30までのバージョンではエラーになる
後述の例が `$small < $medium <= $large` なので、どちらか一方に合わせておいたほうが良いかな？

2020-06-22 19:14 UTC, sironekotoro commented on 2nd/slide.md
> +ただし、2020年にリリースされた Perl 5.32 より、3つ以上の値を同時に比較することが可能になりました。
資料使う時点ではリリースされてるだろう・・・という前提で書いてましたが、思ったより早くてよかった。

2020-06-22 19:17 UTC, sironekotoro commented on 2nd/slide.md
> +```
上記の例の場合、とサラッと書き換えます

2020-06-22 19:20 UTC, sironekotoro commented on 2nd/slide.md
> +if ( $small < $medium < $large ) { # Perl 5.30までのバージョンではエラーになる
確かに、合わせた方がいいですねー、ってことで `<=` に合わせます

2020-06-23 03:34 UTC, tomcha approved these changes
演算子の優先順位はリンクの紹介のみにとどめる感じですね。
その他修正箇所、問題ないかと思います。

2020-06-23 10:33 UTC, xtetsuji approved these changes
修正ありがとうございます！マージします。

2020-06-23 10:33 UTC, merged