Add practce logicaloperator
perl-entrance-org/workshop-basic-online pull request #24
Opened 2020-07-08 23:05 UTC by tomcha

論理演算子の練習問題を追加しました。

2020-07-09 06:30 UTC, xtetsuji requested changes
修正ありがとうございます！

タイプミスがあったので修正提案をしました。その他いくつかコメントしていますが、修正は任意で大丈夫です。

2020-07-09 06:30 UTC, xtetsuji commented on 2nd/slide.md
> +if ($mycard != 7){
追加された前後の文脈を読んでいないのですが、 `!=` 以外の回答として「より小さい」かつ「より大きい」を想定しているということですよね。もしくは `ne` ？

2020-07-09 06:30 UTC, xtetsuji commented on 2nd/slide.md
> +if文の<<条件式>>を書いて、print文通り正しく判定される様に条件式を書いてみよう。
助詞「の」を補った方が個人的に好みかも……。細かくてすみません。

```suggestion
if文の<<条件式>>を書いて、print文の通り正しく判定される様に条件式を書いてみよう。
```

ここの修正は任意で大丈夫です。

2020-07-09 06:30 UTC, xtetsuji commented on 2nd/slide.md
> +  print "青いTシャツを着ていっる又は身長180cm未満の人です。\n";
タイプミスがあったので修正提案。あと「又は」は[開いた表現](https://fluowrite.com/14) の方が一般的な印象があるので、修正提案ではついでに開いた表現にしています。

```suggestion
  print "青いTシャツを着ている、または身長180cm未満の人です。\n";
```

2020-07-09 13:00 UTC, tomcha commented on 2nd/slide.md
> +if ($mycard != 7){
そうです！論理演算子&&と||の練習問題なので、!=7 は「より小さい」||「より大きい」、==7は「7以上（6より大きい）」&&「７以下（８より小さい）」を考えてもらう練習問題です。

2020-07-09 13:08 UTC, tomcha commented on 2nd/slide.md
> +if文の<<条件式>>を書いて、print文通り正しく判定される様に条件式を書いてみよう。
「の」を使った方が読みやすいですね。修正します。

2020-07-09 13:08 UTC, tomcha commented on 2nd/slide.md
> +  print "青いTシャツを着ていっる又は身長180cm未満の人です。\n";
ありがとうございます。開いた表現に直してみます。

2020-07-10 08:21 UTC, xtetsuji approved these changes
修正ありがとうございます！良い感じに修正していただけたのでマージします。

2020-07-10 08:22 UTC, merged