配列リファレンスの練習問題を追加
perl-entrance-org/workshop-basic-online pull request #39
Opened 2020-08-05 23:18 UTC by tomcha

配列リファレンスの練習問題を追加しました。

2020-09-06 15:54 UTC, xtetsuji requested changes
@tomcha 練習問題の追加ありがとうございます！

軽微な修正があったのでコメントしました。それ以外は概ね大丈夫そうです。

以前も触れたアリスとボブ一括変換系などは後日まとめて行いたいと思います。

2020-09-06 15:54 UTC, xtetsuji commented on 4th/slide.md
> +'Alice', 'Bob', 'Chris'の3名が格納された配列リファレンス `$strudents_ref` を、無名配列を使って1行で作成してみよう。
スペルミス strudents → students 修正です。

```suggestion
'Alice', 'Bob', 'Chris'の3名が格納された配列リファレンス `$students_ref` を、無名配列を使って1行で作成してみよう。
```

2020-09-06 15:54 UTC, xtetsuji commented on 4th/slide.md
> +```
これ、ハッシュリファレンスだと O/R Mapper っぽくもありさらに実践的になりそうですね。

ハッシュリファレンスの問題でこのデータを再掲してもいいかもしれません。ただ、そういう流れで導入をすると「ハッシュリファレンスがあれば配列リファレンスは不要なのか」と誤解する受講生もいそうなので、少し考える必要があるかもしれません。

2020-09-07 01:30 UTC, tomcha commented
ありがとうございます。
スペルミス修正しました。

2020-09-07 01:34 UTC, tomcha commented on 4th/slide.md
> +```
ハッシュリファレンスの練習問題として、この配列リファレンスを改造するのは有りかもしれませんね。
%addressbook は1,2,3...をkeyに、各個人のデータはname, telephone,emailをkeyにする感じでしょうか。
問題考えてみます。

2020-09-07 02:39 UTC, xtetsuji commented on 4th/slide.md
> +```
そのような感じです。今回だと

```perl
my @addressbook = (
    ["Alice", "090-123-456", "alice\@perl-entrance.org"],
    ....
);
```

となるところが

```perl
my @addressbook = (
    {name => "Alice", telephone => "090-123-456",  email => "alice\@perl-entrance.org"},
    ....
);
```

となるイメージです。O/R Mapper はまさにこのような「1行を1オブジェクトにする」支援をしてくれるもので、今回はCSVの1行を RDBMS の1行、ハッシュを簡易的なオブジェクトと読み替えると（まさに Perl はそのような世界観ですね）

```perl
for my $address (@addressbook) {
    print "$address{name} の電話番号は $address{telephone} です\n";
}
```

といった可読性の高い書き方が可能になります。

2020-09-07 02:40 UTC, xtetsuji approved these changes
修正ありがとうございます！マージします。

2020-09-07 02:40 UTC, merged