Add practice hashref
perl-entrance-org/workshop-basic-online pull request #42
Opened 2020-08-18 12:43 UTC by tomcha

ハッシュリファレンスの練習問題を追加しました。

2020-09-06 16:08 UTC, xtetsuji requested changes
@tomcha 問題追加ありがとうございます！

軽微な修正のみコメントしました。

2020-09-06 16:08 UTC, xtetsuji commented on 4th/slide.md
> +    telephon  => '090-123-456',
telephon → telephone です

2020-09-07 01:25 UTC, tomcha commented
ありがとうございます。
修正しました。

2020-09-07 02:33 UTC, xtetsuji approved these changes
修正ありがとうございます！マージします。

2020-09-07 02:33 UTC, merged