Add practice regexp
perl-entrance-org/workshop-basic-online pull request #44
Opened 2020-09-06 03:35 UTC by tomcha

サーバーのログを使った正規表現の応用問題を追加しました。
実務のログ処理等、あまり良く知らない部分ではあるので色々ご意見・修正等お願いします。

2020-09-06 16:20 UTC, xtetsuji requested changes
@tomcha 問題追加ありがとうございます！

軽微な修正に関してコメントしました。

正規表現の資料については2012年からほぼ手が入っていないこともあり、内容そのものに関する課題が色々あると思います。第3回は12月開講予定と思われるので、11月末までに私主導で内容に手を入れていきます。

2020-09-06 16:20 UTC, xtetsuji commented on 3rd/slide.md
> +### 練習問題(sturents.pl)
sturents → students ですね。

2020-09-06 16:20 UTC, xtetsuji commented on 3rd/slide.md
> +);
Eve 2個ありますが、Frank を繰り上げてもう1名追加するほうが良いでしょうか。

2020-09-07 01:23 UTC, tomcha commented
アリスボブシリーズのG,Hの該当する名前が無かったので、おさるのジョージから引用してみました。

2020-09-07 02:42 UTC, xtetsuji approved these changes
修正ありがとうございます！マージします。

アリスとボブの名前全般については、第1回目資料の直前で全体統一 Issue を立てて対応したいと思います。

2020-09-07 02:43 UTC, merged