Refix 1st
perl-entrance-org/workshop-basic-online pull request #51
Opened 2020-10-05 09:57 UTC by tomcha

@sironekotoro さんの オンライン版 第1回のリハーサル後の手直しを、現在のmasterに対して適用しました。

2020-10-06 05:45 UTC, sironekotoro approved these changes
ありがとうございます、助かりました。Approveします

2020-10-07 14:28 UTC, xtetsuji requested changes
@tomcha @sironekotoro 対応ありがとうございます！

マージを見送った元々のブランチでコメントすべきでしたが、ここでいくつかレビューしてみました。

クォート忘れで HTML が壊れている部分以外の修正は今必要を感じたら修正するで大丈夫です。

2020-10-07 14:28 UTC, xtetsuji commented on 1st/slide.md
> +- スライド共有ツール（仮）：<a href="https://appslideshare.tugougaii.site/" target="\_blank>appslideshare</a>
スライドでプレビューしたときに HTML タグが丸見えになっていてなんだろうとしばらく見ていたのですが、属性値のクォートの閉じ忘れのようでした。

```suggestion
- コミュニケーション：<a href="https://discord.com/channels/741610576609935430/741610901303721998" target="\_blank"><ruby>Discord<rt>ディスコード</rt></ruby></a>

- スライド共有ツール（仮）：<a href="https://appslideshare.tugougaii.site/" target="\_blank">appslideshare</a>
```

Discord という単語、ここより少し前が初出なのですが、改めて解説ということでルビを振る箇所はここでいいかなと思いました。

2020-10-07 14:28 UTC, xtetsuji commented on 1st/slide.md
> +- PC で スライド共有ツール ・ Wandbox ・ ディスコード を開く
ここ、カタカナの「ディスコード」なのですが、特に理由がなければ Discord に直した方が良いかなと思いました。この後で登場するのも Discord なので。

2020-10-07 14:28 UTC, xtetsuji commented on 1st/slide.md
> +  - 仮想デスクトップ機能・マルチディスプレイなどを用いて、各ツールを切り替える
実際のツール切り替えの動作として想像するのは、ポインティングデバイスで各ウィンドウをクリックするか、Alt + Tab や ⌘ + Tab だと思うのですが、表現が難しいですね。

2020-10-07 14:28 UTC, xtetsuji commented on 1st/slide.md
>  - Discord Perl 入学式チャンネル
今回の Pull Request の変更箇所ではないですがメモとして。

Slack でワークスペースなどと言われるあの単位、Discord での用語は「サーバ」のようです。チャンネルは `#` がつくあっちの方。

「サーバ」と書いて受講生に誤解を与えかねない場合は要検討ですが、対応を考えたいです。

2020-10-07 23:16 UTC, tomcha commented on 1st/slide.md
> +- PC で スライド共有ツール ・ Wandbox ・ ディスコード を開く
確かにそうですね。フリガナ以外はDiscordで統一しましょう。

2020-10-07 23:19 UTC, tomcha commented on 1st/slide.md
> +  - 仮想デスクトップ機能・マルチディスプレイなどを用いて、各ツールを切り替える
おすすめ構成の例のセクションなので、出来る人はこれが便利ということでも良いかと思います。

2020-10-08 10:21 UTC, xtetsuji commented on 1st/slide.md
> +  - 仮想デスクトップ機能・マルチディスプレイなどを用いて、各ツールを切り替える
おすすめ構成をあわせて読むと、意味は伝わりますね。失礼しました！

2020-10-08 10:22 UTC, xtetsuji approved these changes
修正ありがとうございます！マージします。

2020-10-08 10:22 UTC, merged