第2回の分量を削減し、第3回へ回した
perl-entrance-org/workshop-basic-online pull request #54
Opened 2020-10-19 04:19 UTC by sironekotoro

オンライン版第2回は
- スカラー変数
- 四則演算
- 標準入力
- 条件分岐
- 論理演算子
までと想定して編集してみる

2020-10-19 09:12 UTC, sironekotoro commented
コラムは今のところ残しているけど、講義中に時間取れないのではないかなぁ・・・という気がする。

公式ブログとかに移したほうがいいかもしれない

2020-10-20 09:32 UTC, tomcha approved these changes

2020-10-21 12:39 UTC, xtetsuji approved these changes

2020-10-22 09:28 UTC, sironekotoro commented
@tomcha さんが追加してくれた標準入力の練習問題 fight.pl と bot.pl なんですが、主に尺と問題文スペースの都合で復習問題の方に移したほうがいいかも、と言うか移さざるを得ないかもです。

2020-10-22 09:34 UTC, tomcha commented
bot.plは対話形式なので、wandboxでは無理ですね。オンラインでのSTDINは簡単なものしかできないので、hello_stdin.plとcalc.plの２問だけにしても良いかと思います。

2020-10-22 10:59 UTC, sironekotoro commented
条件分岐編も編集終わりました。
講義自体は一旦これをベースに修正していきたいと思います。

あとは、練習問題のいくつかを復習問題として別ファイルに切り出します。

単純な比較ですが、第1回のslide.md は 500行程度、今回は 1700行超です。

2020-11-02 09:43 UTC, tomcha reviewed
全てのcommitに目を通しました。
practice.md の方はまだ「コード」「スクリプト」の表記が残っていました。

2020-11-02 09:43 UTC, tomcha commented on 2nd/slide.md
> +````perl
`が一つ多く、シンタックスハイライトが効いていません

2020-11-02 09:43 UTC, tomcha commented on 2nd/slide.md
> +if ( $foo > 0 && $foo % 2 == 0 ) {```
- \``` を改行
- 閉じ } が必要 
の2つが無いとPerlコード部分を抜けられない？スライド表示はどうなりますか？

2020-11-02 09:43 UTC, tomcha commented on 2nd/slide.md
>  ```
閉じ } 無しでスライドにシンタックスハイライト適用されますか？

2020-11-02 09:43 UTC, tomcha commented on 2nd/slide.md
> +````
\`が一つ多いです

2020-11-02 09:43 UTC, tomcha commented on 2nd/slide.md
> +````perl
\`が一つ多いです

2020-11-02 10:08 UTC, sironekotoro commented on 2nd/slide.md
> +if ( $foo > 0 && $foo % 2 == 0 ) {```
ここは例示用の抜粋部分となり、 `}` は無しとなります。

2020-11-02 10:09 UTC, sironekotoro commented on 2nd/slide.md
>  ```
ここも例示用の抜粋のところです。

2020-11-02 10:14 UTC, sironekotoro commented on 2nd/slide.md
> +if ( $foo > 0 && $foo % 2 == 0 ) {```
こんな感じで、シンタクッスハイライト効きます。
![スクリーンショット 2020-11-02 19 12 54](https://user-images.githubusercontent.com/8675420/97856275-6b94ef80-1d3f-11eb-9566-4fd6021f5122.png)

こちらが、閉じカッコある場合のものです。
![スクリーンショット 2020-11-02 19 13 45](https://user-images.githubusercontent.com/8675420/97856390-8ff0cc00-1d3f-11eb-9595-2518c2bfd580.png)

2020-11-02 10:16 UTC, tomcha commented on 2nd/slide.md
> +if ( $foo > 0 && $foo % 2 == 0 ) {```
スライドでシンタックスハイライト効いておればこのままで問題なしですね

2020-11-02 10:19 UTC, sironekotoro commented
practice.md も、スクリプト・コードをプログラムに置き換えました。

2020-11-02 10:23 UTC, tomcha approved these changes
お疲れさまでした。良いと思います。

2020-11-04 14:23 UTC, xtetsuji requested changes
第2回 2nd/slide.md を重点的に見てみました。

指摘部分は今回の変更部分から漏れているようで、GitHub の行指定コメントがどうも使えないようだったので、この部分でまとめて列挙します。

- 2nd/slide.md
    - レガシーPerl のところ、チルダが打ち消しになっている
        - `参考: <a href="https://speakerdeck.com/anatofuz/regasiperlbirudo-xian-dai-nisu-ruperl-1-2-dot-0toperl6" target="_blank">レガシー Perl ビルド ~現代に蘇る Perl[1..5].0 と Perl6~</a>`
        - 全角チルダ（というか波ダッシュ `〜` ）にすれば大丈夫？
    - メタ構文変数 hoge fuga は国際標準（？）の foo bar buz に寄せる？
    - 1箇所、 `##論理演算子` 、つまり `#` と日本語の間に空白が入っておらず Markdown レンダリング的に失敗している部分がある

必要に応じてオンラインミーティングなどでも議論しましょう。

第3回 3rd/slide.md は第2回終了後のレビューでもいいかなと思いましたが、星2個 `★★` で未定部分が埋められている部分があり、たぶん Discord のことで差し替えればいいかなと考えています。

```
$ grep ★★ 3rd/slide.md
- 講義中に分からない事や疑問点があれば、★★ で質問を発言して下さい。サポーターが適宜回答やアドバイスを行える様にスタンバイしています。
  - うまくプログラムが動かない、分からない時は ★★ でサポーターにヘルプを要請してください。★★ のテキスト及び音声チャットにて個別にサポートします。
```

2020-11-09 02:58 UTC, sironekotoro commented
@xtetsuji 
- アナグラさんのスライドタイトルのチルダ `~` を全角の波ダッシュ `〜` に変更
- 例示プログラム中のメタ構文変数を `hoge`, `fuga` から `foo`, `bar` に変更
- 「1箇所、 ##論理演算子 、つまり # と日本語の間に空白が入っておらず」を修正

11月8日のミーティングで決めた「標準入力をコマンドライン引数にする変更」もこのブランチでやっていきます。

2020-11-09 03:45 UTC, xtetsuji commented
@sironekotoro 修正ありがとうございます！

いったんこれで master にマージします。再度修正が必要であれば、またブランチを切って作業してい

2020-11-09 03:48 UTC, merged