標準入力をコマンドライン引数に変更
perl-entrance-org/workshop-basic-online pull request #56
Opened 2020-11-09 04:50 UTC by sironekotoro

以下をそれぞれコマンドライン変数のものに置き換えました
- 標準入力の解説
- 練習問題

2020-11-09 15:50 UTC, xtetsuji requested changes
@sironekotoro 修正ありがとうございます！標準入力からコマンドライン引数にしても、解説としてはそこまで違和感ないですね。安心しました。

いくつか気になった部分があったので、所定箇所にコメントしました。

`## コマンドライン引数 → ### 入力とは？` 部分のスライド解説の「入力」についての記載がちょっと気になったのですが、これもともとこうだったこともあり、ここでは触れていません。コマンドライン引数に変更してから違和感が……というよりも、標準入力でもこの記載だと若干気になるなぁという感じ。ちょっとこれは修正方針を考えて、私の方から

2020-11-09 15:50 UTC, xtetsuji commented on 2nd/slide.md
> +$ perl hoge.pl arg
Wandbox の Runtime options を入れたときのコマンドライン例が `$ perl prog.pl` なので prog.pl がいいかなと思いました。修正する場合はその他の箇所の hoge.pl も合わせて……ということになりそう。

2020-11-09 15:50 UTC, xtetsuji commented on 2nd/slide.md
> +$ perl hoge.pl arg1 arg2
シェルでは裸のワード (bare word) はクォートしなくても一塊の引数文字列となるルールなのですが、Perl の `use strict` 時の文法や Wandbox の例示、あと空白が入ったときに説明が面倒なこともあるので、最初からクォートで括った解説にしておいた方が良いかもなと思いました。

```suggestion
$ perl prog.pl "arg1" "arg2"
```

講義中に必要があれば、空白文字等が入らなければクォートを省くことができることに触れましょう。

ダブルクォートは Wandbox の例示に合わせたのですが、ドル記号があるとシェル変数を展開してしまう点は要注意かも。とはいえPerl入学式のカリキュラムでは空白文字の混入と比べると危険性は少ないのでスルーで良いかも。

`s/hoge/prog/` しています。別のコメント箇所を参照下さい。

2020-11-09 15:50 UTC, xtetsuji commented on 2nd/slide.md
> +my $foo = shift;  # コマンドライン引数から値を1つ受け取り、変数 $foo に代入する
どの値を取得できるのか書いたほうが良さそうです。

```suggestion
# コマンドライン引数から一番左側の値を1つ受け取り、変数 $foo に代入する
my $foo = shift;  
```

コメントが長くなったので別行立てしました。

この変更を適用するのであれば、次の `my $bar = shift;`  部分は「左から2番目の値」といった表現が適切かと思います。

2020-11-09 15:50 UTC, xtetsuji commented on 2nd/slide.md
> +```bash
単純な出力を扱うことになるので、フォーマットは bash ではなく plaintext 系の方が良い？

2020-11-10 00:36 UTC, sironekotoro commented on 2nd/slide.md
> +$ perl hoge.pl arg
自分もそう思ったのですが、 `hoge.pl` 使ってたのここだけでした

2020-11-10 01:03 UTC, sironekotoro commented on 2nd/slide.md
> +```bash
確かに。plaintext に変更しました

2020-11-10 01:12 UTC, sironekotoro commented on 2nd/slide.md
> +$ perl hoge.pl arg1 arg2
コマンドライン側はクォーテーションで括ったものを引数にします。

Wandbox はクオーテーションで括った引数にすると、クオーテーションごと取り込まれるみたいです。
ターミナルではクォーテーションあり、 Wandbox ではクオーテーションつけなくでもやってくれる、的な感じで説明ですかね。
https://wandbox.org/permlink/zohHFUdTokU6d6L1

2020-11-10 03:51 UTC, xtetsuji commented on 2nd/slide.md
> +$ perl hoge.pl arg1 arg2
Wandbox は改行文字を引数のデリミタとして扱う以外、その他の文字はあるがままに扱うということなのでしょうね。改行文字は通常は引数に入ることもないし、合理的な仕様ですね。

2020-11-10 12:56 UTC, xtetsuji commented
修正をプッシュしました。これで大丈夫そうであれば明日にもマージします。

もうちょっと修正が必要という場合は、ここのコメントでお知らせ下さい。

2020-11-11 02:32 UTC, sironekotoro commented
修正大丈夫そうです！ありがとうございます。

2020-11-12 02:48 UTC, merged

2020-11-12 02:49 UTC, xtetsuji commented
マージしました。引き続き必要な修正がある場合はブランチ作成して対応していきましょう！