Edit for online 3rd
perl-entrance-org/workshop-basic-online pull request #57
Opened 2020-11-16 06:55 UTC by sironekotoro

- オンライン版の第三回の修正です
    - 配列
        - for文
        - fizzbuzz
    - 配列を使った関数
    - ハッシュ
    - ハッシュを使った関数

- 正規表現の部分は手をつけていません。
    - 正規表現は次回以降に回し、かつ簡略化するということで、どうでしょう？

2020-11-16 16:03 UTC, xtetsuji commented
@sironekotoro 修正ありがとうございます！

> 正規表現は次回以降に回し、かつ簡略化するということで、どうでしょう？

それで大丈夫です。正規表現カリキュラム作り直したいと言いつつ作り直せていなかったので、4th/slide.md で先行して正規表現カリキュラムを私の方で作成するといいかもしれませんね。

あとこの Pull Request の後でもいいですが、第2回資料 2nd/slide.md はもともと if 文とかの解説がなかった、第3回にあるという状態にしてもいいかなと思いました。後で振り返って実際の配分がわかりやすいかなと思ったりしたことや、当日2個のスライドを切り替えるのも手間かなとも。必要に応じてオンラインミーティングやチャットで議論しましょう。

修正範囲のレビューは後ほど行います。

2020-11-17 02:07 UTC, sironekotoro commented
@xtetsuji 
>当日2個のスライドを切り替えるのも手間かなとも。必要に応じてオンラインミーティングやチャットで議論しましょう。
この視点はなかったです。

後ほど、IF文を加え、正規表現を外したものをアップします。

2020-11-17 03:04 UTC, xtetsuji requested changes
@sironekotoro 修正ありがとうございます！

ざっと見たところ新たに気になったところはなかったのですが、一点コメントしておきました。

私が言い出しっぺではありますが、if 文まわりごそっと 2nd/slide.md → 3rd/slide.md 移動したら diff としては変更範囲大きくなってしまいましたね。大きな diff になるとレビューの見通しが悪くなるかもしれないので、一段落したらいったんマージするかなど別途相談させて下さい。

2020-11-17 03:04 UTC, xtetsuji commented on 3rd/slide.md
> +- 配列の操作（join, split, push, pop, unshift, shift, reverse sort）
reverse と sort は別個なので、ここもカンマで区切るのが良さそうですね。

```suggestion
- 配列の操作（join, split, push, pop, unshift, shift, reverse, sort）
```

2020-11-17 03:08 UTC, sironekotoro commented
@xtetsuji 
コメントありがとうございます。いやー、GitHub上で修正適用できるの楽でいいですわ。

if文はそのまま持ってきましたが、一旦これでマージして、マージ後にオンライン用に削ぎ落としていくってのがいいと思いました。

2020-11-17 03:25 UTC, xtetsuji commented
@sironekotoro GitHub 様様 :pray: ですね。

私、実はレビューされる側に回ったことがなくて Suggestion を GitHub 上で適用する方を体験したこと無いのですが、もしコミットメッセージの変更機能があるのであれば、変更点の要約にしておきたいなと思いました。今のところ大丈夫だと思うのですが、これを繰り返すと `git log` に `Update ファイル名` がひたすら並ぶのは後々つらいかな〜と思いまして。

2020-11-19 10:24 UTC, tomcha approved these changes

2020-11-29 06:18 UTC, xtetsuji commented
さらに細かくみたいな〜とも考えていますが、ファイル間移動があったことで diff も多いこともあり、いったんここでマージしたいと思います。必要に応じて私も Pull Request 作成予定です。

2020-11-29 06:18 UTC, merged