サブルーチンの練習問題を追加
perl-entrance-org/workshop-basic-online pull request #64
Opened 2021-01-16 12:45 UTC by tomcha

サブルーチンの練習問題を追加しました。

2021-01-18 02:19 UTC, xtetsuji requested changes
@tomcha 修正ありがとうございます！

いくつか気になったところにコメントしてみました。

2021-01-18 02:19 UTC, xtetsuji commented on 4th/slide_online_4th.md
> +    print "nPerlのイベントJapan.pmがオンラインで開催されます!\n";
文字列リテラル冒頭の `n` は混入したものと思われるので、除去したほうが良さそうですね。

ここの問題に限らず本編の解説にも言えることですが、サブルーチンの中で `print` する（標準出力への出力という副作用を引き起こす）のか `return` するのかという部分は、本編の中でビシッと言いたいかもなぁと思いました。正規表現と合わせて、サブルーチンもPerl入学式始まってからあまり手を入れられていないので、次シーズンまでに色々手を入れたいなぁと。

2021-01-18 02:19 UTC, xtetsuji commented on 4th/slide_online_4th.md
> +    print "$nameさん、Perl入学式へようこそ!\n";
`$name` と、その後に続く文字列が空白で区切られていない場合、素の Perl コードだと大丈夫なのですが、 `use utf8;` して utf8 プラグマを有効にすると

```
Global symbol "$nameさん" requires explicit package name (did you forget to declare "my $nameさん"?)
```

になってしまいます。utf8 プラグマ有効時だと、日本語のひらがななども変数名を構成しうる文字となることによります。なお、日本語の句読点等の約物類は変数名を構成しうる文字ではないので `$nameさん` までが変数だと解釈されています。

これを回避するためには

- この場合においては `$name` ではなく `${name}` と書く
- `printf "%sさん……", $name` といった方法を取る
- `print $name . "さん……"` といった感じで `$name` を分離する
- 空白文字が入ることに問題がなければ `"$name さん……"` と`$name` と `さん` の間に空白を入れる

といった方法が必要になりますが、最初の2個は教えていない、教えることが増えるという点で採用するか悩ましいところ。3番目の `$name . "さん……"` は、今まで `$` 変数は `""` 内に入れれば自然に展開されるという文脈において不自然な感じもするので、ちょっとイマイチかなぁという感じもしています。

特によいアイデアがなければ、4番目の間に空白を入れる方法で対応したいです。

2021-01-18 10:04 UTC, tomcha commented on 4th/slide_online_4th.md
> +    print "$nameさん、Perl入学式へようこそ!\n";
. 演算子で文字列連結が良いかなーと思っていたのですが、スカラー変数の資料でたしか""の中で変数を展開していたのでこの書き方にしていました。
上記の問題を考慮すると、 . 演算子で連結するのが良いのではないでしょうか。

2021-01-18 10:07 UTC, tomcha commented on 4th/slide_online_4th.md
> +    print "nPerlのイベントJapan.pmがオンラインで開催されます!\n";
n、Typo修正します。
return 学習前の段階での練習問題なので、print文を使いました。
何か関数に仕事をさせるだけで返り値を求めない例があればよいのですが、受講者が目に見えてわかるのが結局print文しかないのかなぁということでprint文を選択しました。

2021-01-18 12:33 UTC, xtetsuji commented on 4th/slide_online_4th.md
> +    print "$nameさん、Perl入学式へようこそ!\n";
そうですね〜。個人的に `print $name . "さん……";` はパッと見てドキッとする構文なんですよね。間接オブジェクトスロットにファイルハンドルを置いて書き込む構文 `print $fh "書き込み文字列\n"` と似ているから……？

いったん `print "$name さん……"` という空白を入れる作戦にしましょう。重箱の隅指摘ではありますが、utf8 プラグマが無効であれば `"$nameさん……"` でも問題がないので、受講生の将来的な心配という面が大きいです。この辺りは、講義中の中でも触れたいと考えています。

2021-01-18 23:11 UTC, tomcha commented on 4th/slide_online_4th.md
> +    print "$nameさん、Perl入学式へようこそ!\n";
了解です。

2021-01-19 02:35 UTC, xtetsuji approved these changes
@tomcha 再び修正ありがとうございます！最初に目に留まった部分は全て解決したのでマージします。

2021-01-19 02:35 UTC, merged