2021 2nd slide
perl-entrance-org/workshop-basic-online pull request #81
Opened 2021-05-15 08:17 UTC by sironekotoro

2021年度の第2回のテキストです。

前回差分と大きくなるので、別ファイルである `new_slide.md` を作成してそちらで編集し、okが出たらもとの `slide.md` と置き換えます。

スライド枚数は今の所77枚です。

- 練習問題の数
    - if文 + 比較演算子: 2 
    - if文 + 論理演算子: 1
    - for文 + if文: 1

2021-05-15 11:24 UTC, xtetsuji requested changes
@sironekotoro 修正ありがとうございます！レビューしてみました。

2021-05-15 11:24 UTC, xtetsuji commented on 2nd/new_slide.md
> +print $second;         # $second を表示する
この部分、実際に実演すると `$first` と `$second` が同じ行で連結されるので、ちょっと見づらい（？）と思う反面、それを想定して改行を入れることを教える想定もありますね。

2021-05-15 11:24 UTC, xtetsuji commented on 2nd/new_slide.md
> +あくまで、Perl では先に述べた 5 つの偽値のみが偽、それ以外はすべて真となります。
ここの部分をじっくり読んでいたのですが、表現としては「表すことはできません」というよりも「表すような組み込みの記法は存在しません」なのかなぁと思いました。 `use constant true => 1` などしている例はたまに見かけるので。

これは上級向けになりますが、[overload](http://perldoc.jp/overload)されたオブジェクトは真偽判定を独自実装できるので、これのみという断定は少し弱めて後につなげると良さそう？

真の代表値が 1 であることは前のスライドで解説しましたが、偽の代表値をここで例示すべきかはちょっと悩みますね。サブルーチンを学んだ後は、 `return;` で何も返さないことが偽のテクニックとなるので、そことの兼ね合いも考えたり。

上記の注釈として、サブルーチンで偽を返すために `return undef;` と書かないほうが良い理由は、このようなサブルーチンをリストコンテキストで呼んだ場合、 `@arr = func();` で `@arr = (undef);` と同じ意味になってしまい、この配列 `@arr` の真偽値評価は真となるためです。サブルーチンの `return;` であれば、リストコンテキストでは空リストが返されるので、配列は空となり偽となります。

私自身、文章表現に自信がないですが、案を書いてみました。ミーティング等で議論しましょう。

```suggestion
他のプログラミング言語では、<ruby>`true`<rt>トゥルー</rt></ruby> や <ruby>`false`<rt>フォルス</rt></ruby> という単語に 真 または 偽 の意味を持たせたキーワードとして扱うことがあります。

しかし、Perl は `true` や `false` といった、ひと目で真偽値であることがわかる組み込みのキーワードはありません。

Perl では先に述べた 5 つの偽値のみが偽、それ以外は真となります。
```

2021-05-15 11:24 UTC, xtetsuji commented on 2nd/new_slide.md
> +この場合、実行すると以下のエラーが出ます。
ここは strict によるエラーではなく、warnings による警告ですね。エラー、いわゆる例外やコンパイルエラー等で終了せず、処理は続行されます。

上の `my $num == 1` もエラーではなく警告のよう。

2021-05-16 13:21 UTC, sironekotoro commented on 2nd/new_slide.md
> +print $second;         # $second を表示する
ここは直前にやった文字列連結も兼ねて以下のようにしてみました
```perl
print 'first is ' . "$first\n";      # $first を表示する
print 'second is ' . "$second\n";    # $second を表示する
```

2021-05-16 13:36 UTC, sironekotoro commented on 2nd/new_slide.md
> +あくまで、Perl では先に述べた 5 つの偽値のみが偽、それ以外はすべて真となります。
true/false については 出していただいた案が良いと思います。キーワードってのが特に良いと思いました。

偽値は確かに、難しいですね。
サブルーチンの回で「サブルーチンが偽を返すときは `return` のみです」って説明を入れるってとこですかね。

感覚でわかる身になってしまったんだけど、このコンテキストを言語化するのは面倒そう。
```perl
my $s = func();
if ($s) {
    print "scalar true\n";    # 表示さない
}

my @a = func();
if (@a) {
    print "array true\n";     # 表示される
}

sub func {
    return undef;
}
```

2021-05-16 13:55 UTC, sironekotoro commented on 2nd/new_slide.md
> +この場合、実行すると以下のエラーが出ます。
ですね、ここは警告に直します。

2021-05-17 04:04 UTC, xtetsuji commented on 2nd/new_slide.md
> +print $second;         # $second を表示する
ここの部分であれば

```perl
print "first is $first\n";
print "second is $second\n";
```

とかでも良さそうですね。

この部分、以前にどこかで `print "値は$valueです\n";` みたいな例があって、`not utf8` または `use bytes` 環境では `print "値は${value}です\n";` と同じだけど、 `use utf8` 環境では多くの日本語文字も変数として使用可能なので `print "値は${valueです}\n";` と解釈されるという部分で、後々混乱しないように変数と文字列リテラルは分けて `.` で連結しましょうとなった記憶があるのですが、ここの部分は難しいですね。受講生によっては、ダブルクォーテーション中に埋め込めばいいだけなのにわざわざ煩雑な書き方をしている、と見る人もいそう。

`print` 関数が任意引数で任意個の文字列を受け取って内部的に空文字で（ `$,` が定義されていれば `$,` で）連結することを除外すると、上記の分割して演算子で連結か、ダブルクォーテーション中に埋め込みかは、コラムとかである程度正直に書いた方がいいかもなぁと感じました。ちょっと時間を取ってオンラインミーティング等で議論検討したいので、ここでは現在のままで大丈夫です。

2021-05-17 04:17 UTC, xtetsuji commented on 2nd/new_slide.md
> +あくまで、Perl では先に述べた 5 つの偽値のみが偽、それ以外はすべて真となります。
「キーワード」とか「トークン」といった言葉、「そう書かれたもの」といったふわっとした伝え方が誤解や曲解もほぼなくできる（他の用語は公式によって既に別の意味として使われていることがある）ので、プログラミング解説で困ったときに使いますね。

コンテキストは初学者だけでなく上級者もたまにハマるPerlの鬼門とも言えそうなので、ベーシック版ではうかつに踏み込まない方が良さそう……。以前から私がやりたい言っていることではあるのですが、初学者に感覚的に伝えるためには Visual Studio Code の拡張機能などを作ってコンテキストに色を付けると良いのかなと考えています。というかそういう拡張機能があったら私が使いたい。

```perl
# スカラーコンテキストが背景茶色、
# リストコンテキストが背景水色としたとき

for my $user (@users) { # ここの @users は背景水色で表示される
    ...
}
if ( @users ) { # ここの @users は背景茶色で表示されてツールチップが出る
    say "ユーザがいませんでした";
}
if ( $answer ) { # スカラーコンテキストにスカラーを置いている（多くの場合）単純な場合なので、ここは何も示唆しない
    ...
}
```

2021-05-17 04:30 UTC, xtetsuji approved these changes

2021-05-17 04:34 UTC, xtetsuji commented
@sironekotoro 追加の修正ありがとうございます！

昨年度以前からの記載も含めて要検討箇所はありましたが、今回の Pull Request はいったんマージして、細かい修正は追って施していけばいいかと思いました。

`git mv` でリネームしてからマージかなと思ったので、いったん私の方ではマージまわりの操作は保留することにしました。

2021-06-14 14:48 UTC, sironekotoro commented
`git mv` で new_slide.md を slide.md に上書きしました。これで一旦マージしてしまいます。

2021-06-14 14:49 UTC, merged