第4回スライド作成
perl-entrance-org/workshop-basic-online pull request #87
Opened 2021-09-29 01:39 UTC by sironekotoro

- 個々のスライドを部品・章単位で作成し、 `text_source` フォルダーにまとめた
    - フォルダー名や位置については議論の余地があるかも
    - 雑に作った `cat.pl` で結合してリダイレクトで `slide.md` を作成

- リファレンス・正規表現ともにオフライン版から一新している
    - リファレンスは間接参照の詳細な説明を抑え、実用ベース
    - 正規表現はWeb+DB Press vol.113 の Perl Hackers Hub の最初の方を詳細に説明した感じ

2021-10-16 12:04 UTC, tomcha commented on text_source/title.md
> +## リファレンス / サブルーチン 編
リファレンス / 正規表現 編　になるかと

2021-10-16 12:08 UTC, sironekotoro commented on text_source/title.md
> +## リファレンス / サブルーチン 編
ありがとうございます、修正しました！

2021-11-05 12:53 UTC, xtetsuji requested changes
レビュー、遅れてしまいすみません。

リファレンスと正規表現、それぞれ気になった部分をコメントしてみました。

正規表現の問題で考え中の部分は、状況を見ながら明日即席で何か入れましょうかね。

2021-11-05 12:53 UTC, xtetsuji commented on 4th/slide.md
> +|  name   | Japanese | math |
表のヘッダ部分、Japanese だけ頭文字大文字ですが、name や math も Name や Math にしてしまってもいいかも。

2021-11-05 12:53 UTC, xtetsuji commented on 4th/slide.md
> +```
うまく行かないこと、派手にエラーを見せたほうがいいのかなと思ったのですが、それによって誤解を与えそうな気もするし悩ましさはありますね。

例えばこの `@array` に対して Bob の math を取ろうと `$array[1]{math}` とすると `Can't use string ("name") as a HASH ref while "strict refs"` エラーが出るはず。

修正方針が固まらなければ、当日の講義中に補足を入れる方向で行きましょう。

2021-11-05 12:53 UTC, xtetsuji commented on 4th/slide.md
> +アロー記法を用いると、デリファレンスをすることなくデータを取り出すことが可能です。
アロー記法はシジルによるデリファレンスをショートカットして各要素へアクセスできるのですが、デリファレンスしている（参照元をたどっている）ことに変わりはないので、少し表現を変えたいところ……。

「デリファレンスをすることなく」のところ、「参照元に対応したシジルをつけることなく」とかですかね。

2021-11-05 12:53 UTC, xtetsuji commented on 4th/slide.md
> +アロー記法でも、添字 `[0]` や ハッシュの名前 `{name}` など、それぞれの変数に応じた記法を用います。デリファレンスと同様に、元データが配列であるかハッシュであるかを意識しておくことが大事です。
「名前」より「キー名」「キー指定」の方が良さそう。

「キー指定」にするのであれば、配列の方でも「添字指定」にすると統一感が取れるかも。

あと、この段階で資料に入れる必要はないのですが、講義時間に余裕があれば、リファレンスの参照元が配列かハッシュかを判断する `ref` 関数があるけれど、通常は使わない、配列リファレンスかハッシュリファレンスかは別途把握する、ということも解説してもいいかも。

2021-11-05 12:53 UTC, xtetsuji commented on 4th/slide.md
> +また、Perl の記述法を利用して正規表現機能を提供しているソフトもあり、これらで提供している正規表現は PCRE(Perl Compatible Regular Expressions) と呼ばれています。
利用というよりも、参考にして真似ているというニュアンスですかね。PCRE の中に入っている「互換」がまさにそれなのかも。

coreuitls の grep などに見られる BRE や ERE には無い、Perl から生まれた先後読みなどを念頭に置いています。

修正例を考えてみました。

```suggestion
また、Perl から生まれた有益な正規表現の文法を提供しているソフトもあり、これらで提供している正規表現は PCRE(Perl Compatible Regular Expressions) と呼ばれています。
```

講義資料に記載するかコラムに記載するかは要検討として、Perl の正規表現は他の正規表現と互換性が無いどころか、20年ほど前に様々な言語やライブラリが Perl の正規表現を取り入れて、正規表現といえば PCRE とまで言えるようになったということは Perl の功績としてアピールしてもいいかもしれません。

2021-11-05 12:53 UTC, xtetsuji commented on 4th/slide.md
> +    対象の文字列を、正規表現で表せること。
通情の文字列検索での「合致する」の正規表現版ではあるのですが、表現が難しい。あと、冒頭 ^ や末尾 $ が無い場合は部分文字列を探すことになるのも考慮に入れたいところ。

正規表現を主語にした方がいいかな〜。

例えば「正規表現が意図する文字列の並びの一つが、対象の文字列中に含まれる」とかですが、書いてみて難解……。

講義資料を修正しない場合も、正規表現を文字列検索になぞらえたときに「見つかった」ということを表しているということが伝われば、この段階では十分かと思います。

2021-11-05 12:53 UTC, xtetsuji commented on 4th/slide.md
> +連続した文字であれば、`[a-e]`のように書くことも可能です。
連続した文字の定義、文字コード上であることも補足しておくと良さそう。

2021-11-05 12:53 UTC, xtetsuji commented on 4th/slide.md
> +```
ここ、 `/^p/` より `/^r/` の方が面白そう。 `'perl'` も `r` を含んでいますが、 `'ruby'` にしかマッチしないことで冒頭 `^` のありがたみが分かりそうです。

2021-11-05 12:53 UTC, xtetsuji commented on 4th/slide.md
> +```
資料に書くか、講義の中のやり取りでやるかは要検討ですが、数値部分をキャプチャしてバージョン番号を取り出すサンプルも良さそう。

2021-11-06 04:27 UTC, sironekotoro commented on 4th/slide.md
> +アロー記法でも、添字 `[0]` や ハッシュの名前 `{name}` など、それぞれの変数に応じた記法を用います。デリファレンスと同様に、元データが配列であるかハッシュであるかを意識しておくことが大事です。
とりあえず、キー名です

2021-11-06 04:27 UTC, sironekotoro commented on 4th/slide.md
> +アロー記法を用いると、デリファレンスをすることなくデータを取り出すことが可能です。
> アロー記法を用いると、参照元に対応したシジルをつけることなく、簡易な記法でデータを取り出すことが可能です。

こんな感じにしようと思います

2021-11-06 04:28 UTC, sironekotoro commented on 4th/slide.md
> +```
ここはエラーというより、「配列の配列」にならない、配列がflatになってしまうということ示したかったところです。
説明で補足しつつ良い言い回し検討ですね

2021-11-06 04:30 UTC, sironekotoro commented on 4th/slide.md
> +    対象の文字列を、正規表現で表せること。
わかりやすさ優先で「正規表現に合致する文字列を見つけること」にしようかと思います。

2021-11-06 04:40 UTC, xtetsuji approved these changes
@sironekotoro 修正ありがとうございます！マージしますね。

2021-11-06 04:40 UTC, merged