2021年度オフライン版 第1回スライド
perl-entrance-org/workshop-basic-online pull request #89
Opened 2021-11-10 15:02 UTC by sironekotoro

- `slide.md` の差異が大きくなるため、`new_slide.md` を作成しています。問題がなければ `slide.md` と置き換える形のP/Rを追加します。
- 2021年オンライン版をベースに、細かい修正、perldoc張り替え、などです。
- WANDBOX説明、ターミナル操作 〜 配列（fizzbuzz）まで。
- 総スライド数：162
- すみません、Git の設定が吹っ飛んだままでした $GIT_AUTHOR_NAME は sironekotoro です。

2021-11-12 02:18 UTC, xtetsuji requested changes
@sironekotoro 修正ありがとうございます！

オン・オフ共用を目指したということ、また前期の資料を踏襲していることもあり、特に両者で変わらない各単元の内容自体は深く見ていません。具体的には Visual Studio 入門以降はコメントはありませんでした。

オンライン記述はオフライン開講時には飛ばす運用になると想定しています。

レビューし始めた時はファイル分割されていると想定しておらず、便宜的に 1st/new_slide.md にコメントしています。

全体的な感想として……

スライド全部で161ページ。オフラインだと受講生の理解具合に依存しやすい傾向がありますが、通常ペースであれば4時間だと100ページ前後かなと考えています。このあたり、飛ばす運用や今回の受講生の進捗具合を見ながら、次回以降の方針を決められればと考えています。

ファイル分割を単元や節ごとに進めた場合、オン・オフで結合ルールを変える仕組みがあるといいかもしれないと思いつつ、一方のファイル名が slide.md ではない場合にはスライド同期くんの考慮が必要だなとも思いました。結合ルールを別途管理する案など、オンラインミーティング時に議論できればと考えています。

2021-11-12 02:18 UTC, xtetsuji commented on 1st/new_slide.md
> +それぞれのツールへのリンクは <a href="https://perl-entrance.connpass.com/event/189331/" target="_blank">connpass のイベントページ</a>に掲載しています。
ここのリンク、2020年10月秋開講のものですが、リンク提供をする上では特に問題ないかな。

ゆくゆくはPerl入学式サイト上にツール紹介ページを作りたいですね。

2021-11-12 02:18 UTC, xtetsuji commented on 1st/new_slide.md
> +- 講義スライド共有：<a href="https://appslideshare.tugougaii.site/slide/Online2020?p=1&c=pre-left&cf=1" target="_blank">スライド同期くん</a>
リンク中 2020 だったのでアクセスしてみたところ、2020 でも 2021 でも同じものが出るようです。いちおう 2021 にしておくのが無難ですかね…？

なお、2020年度当時の講義資料は、Git タグでひっぱるか、そもそもたどることは無いと割り切るか……このあたりは以前も議論してタグルールの策定ができていないだけなので、私の方で頑張ります。

2021-11-12 02:18 UTC, xtetsuji commented on 1st/new_slide.md
> +まずは 30 秒を基準にして設定し、Youtube Live で配信される講師スライドに合わせて調整を行ってください。
今回はオフラインのための修正なので備忘録的ではありますが、最近は超低遅延配信がうまくいっているので、次回のオンライン第1回にはここの「30秒」部分の記載もうまい具合にしたいですね。

2021-11-12 02:18 UTC, xtetsuji commented on 1st/new_slide.md
> +## コマンド集（cd）
細かい指摘ですが、ここの前の `mkdir` は `` `mkdir` `` とバッククォート囲みになっているのですが、ここからバッククォート囲みでなくなっていますね。

どちらかに合わせておきたいかも。

2021-11-12 07:21 UTC, sironekotoro commented on 1st/new_slide.md
> +それぞれのツールへのリンクは <a href="https://perl-entrance.connpass.com/event/189331/" target="_blank">connpass のイベントページ</a>に掲載しています。
せっかくなので今回のconnpassページに変更しておきました。

2021-11-12 07:21 UTC, sironekotoro commented on 1st/new_slide.md
> +- 講義スライド共有：<a href="https://appslideshare.tugougaii.site/slide/Online2020?p=1&c=pre-left&cf=1" target="_blank">スライド同期くん</a>
念の為、2021に変えておきました

2021-11-12 07:22 UTC, sironekotoro commented on 1st/new_slide.md
> +## コマンド集（cd）
バッククォート囲みで統一しました

2021-11-12 09:18 UTC, xtetsuji requested changes
@sironekotoro 再度修正ありがとうございます！

今回も便宜上 1st/new_slide.md の方のみにコメントしています。

1箇所、修正ミスっぽいところがあったのでコメントしました。それ以外は大丈夫そうです。修正できたらマージ予定です。

2021-11-12 09:18 UTC, xtetsuji commented on 1st/new_slide.md
> +それぞれのツールへのリンクは <a href="https://perl-entrance.connpass.com/event/228086s/" target="_blank">connpass のイベントページ</a>に掲載しています。
修正ありがとうございます！

1文字多く入っちゃっているかも……？

```suggestion
それぞれのツールへのリンクは <a href="https://perl-entrance.connpass.com/event/228086/" target="_blank">connpass のイベントページ</a>に掲載しています。
```

2021-11-12 09:39 UTC, sironekotoro commented on 1st/new_slide.md
> +それぞれのツールへのリンクは <a href="https://perl-entrance.connpass.com/event/228086s/" target="_blank">connpass のイベントページ</a>に掲載しています。
おっと、修正します

2021-11-12 12:37 UTC, xtetsuji approved these changes

2021-11-12 12:37 UTC, merged

2021-11-13 04:48 UTC, xtetsuji commented
1st/new_slide.md -> 1st/slide.md のリネームを行っていなかったので、 #90 で対応しました。