2021年度オフライン版 第2回スライド
perl-entrance-org/workshop-basic-online pull request #92
Opened 2021-11-20 17:15 UTC by sironekotoro

- 2021年オンライン版をベースに、細かい修正、perldoc張り替え、などです。
- 配列操作、ハッシュ、ハッシュ操作、サブルーチンまで。
- 総スライド数：80（タイトルや注意書きなどを含まない）

2021-11-26 10:24 UTC, xtetsuji requested changes
@sironekotoro 修正等ありがとうございます！

今回は以前の資料の分割がメインっぽそうだったので、中身はざっと流し読みして、最低限のコメントにしています。

分割ファイルの結合処理部分、Makefile を使った方法を記載しておきました。必要でしたら取り入れてみて下さい。

2021-11-26 10:24 UTC, xtetsuji commented on text_source/12__array_functions.md
> +配列のデータを処理するパターンとして <ruby>LIFO<rt>ライフォ</rt></ruby> ,<ruby>FIFO<rt>フィフォ</rt></ruby> があります。
私は LIFO のことを「リフォ」って言っているのですが、ライフォ `/ˈlaɪfoʊ/` が正式なんですね。

- [LIFO - Wiktionary](https://en.wiktionary.org/wiki/LIFO)

これのリンクから FIFO を調べてみたら

- [FIFO - Wiktionary](https://en.wiktionary.org/wiki/FIFO)

発音記号で `/ˈfaɪ.foʊ/` と書かれていて、これは「ファイフォ」では……という気も……。

SQL とか、欧米では「シィークェル」って言っているけれど、日本で「シィークェル」って言っても誰にも通じないので、欧米の発音は参考としつつ、発音については講義内やコラムで補った方がいいかもしれませんね。

2021-11-26 10:24 UTC, xtetsuji commented on text_source/concat.pl
> +# perl concat.pl title.md header.md 12__array_functions.md 13__hash.md 14__hash_functions.md 15__subroutin.md footer.md > ../2nd/new_slide.md
私の方で新規ファイル追加をすると @sironekotoro さんの手元を混乱させてしまう（Fork リポジトリからの PR なのでなおさら私のコミットを途中で取り入れるすべがない）ので、コメントでアドバイスしておくと、以下のような Makefile を書いておくと結合ファイルの外部管理が可能です。

```makefile
FILES_DAY2	= title.md header.md 12__array_functions.md 13__hash.md 14__hash_functions.md 15__subroutin.md footer.md

usage:
	@echo "Usage:"
	@echo "  make ../2nd/new_slide.md"

../2nd/new_slide.md: $(FILES_DAY2)
	perl concat.pl $(FILES_DAY2) > $@
```

このような text_source/Makefile を作成して `cd text_source` したあと `make` を打つと、一番最初のターゲットである `usage` が実行されてヘルプが出ます。指示通り `make ../2nd/new_slide.md` を打つと結合が行われるという寸法です。実際に `make` コマンドでどんなコマンドが発行されるかだけ知りたい場合は `-n` オプションを付けて `make -n ../2nd/new_slide.md` とすると良いです。

この make のやり方のうまいところは、 `$(FILES_DAY2)` の全てのファイルの mtime より `$@` であるターゲットの `../2nd/new_slide.md` の方が新しい場合は `make ../2nd/new_slide.md` と打っても「ファイルは最新（なので何もしない）」と言われるところです。

結合ファイルの一覧は Makefile 内で管理しておけばよいのも都合がいいかなと思いました。必要であれば取り込んでみて下さい。

2021-12-07 00:49 UTC, sironekotoro commented on text_source/12__array_functions.md
> +配列のデータを処理するパターンとして <ruby>LIFO<rt>ライフォ</rt></ruby> ,<ruby>FIFO<rt>フィフォ</rt></ruby> があります。
読み仮名のところに併記して書いておきます

2021-12-07 01:38 UTC, sironekotoro commented
@xtetsuji Makefile 参考にさせてもらいました。ターゲット名をそのまま変数にできるってのは知らなかったです。わかりやすくていいですね。

コラムも追加しました。追加した2冊は独断で入れております。

2021-12-09 14:01 UTC, xtetsuji approved these changes
@sironekotoro 修正ありがとうございます！

気になったポイントにコメントしてみましたが、Approve なので slide.md 生成後にマージ OK です。

57d7dabeebb9debce1bc682c29fc824b6a0becbe が気になったのですが、直近オンライン第5回編集とぶつかった感じですかね。差分自体はほとんど無かったので特に影響はないと考えています。

2021-12-09 14:01 UTC, xtetsuji commented on text_source/title.md
> +## ハッシュ/サブルーチン編
今回はこのままで良さそうですが、 `title1.md` から `title5.md` まで作って、各回それぞれの表紙を別管理にしてもいいかもしれませんね。

2021-12-10 01:53 UTC, sironekotoro commented on text_source/title.md
> +## ハッシュ/サブルーチン編
https://github.com/perl-entrance-org/workshop-basic-online/pull/92/commits/57d7dabeebb9debce1bc682c29fc824b6a0becbe ですが、第5回の `title.md` がぶつかったのでした。

`title.md` 平行進行時のコンフリクトの可能性があるので、各回ごとにファイル作ってよさそうですね。

2021-12-10 02:18 UTC, merged