2021年度オンライン版 第5回スライド
perl-entrance-org/workshop-basic-online pull request #93
Opened 2021-11-21 17:39 UTC by sironekotoro

- 完全新規の内容です。
    - HTTP::Tiny による GET実習 として気象庁非公式API
    - HTTP::Tiny による POST実習としてDiscord Webhook
- 総スライド数：34（タイトルや注意書きなどを含まない）
    - 流石に少なすぎるので、前回（リファレンス、正規表現）の復習問題をやるとかしないと時間がもたない？
- approve が出たら、slide.md を生成してマージする

2021-11-26 10:04 UTC, xtetsuji requested changes
@sironekotoro 新カリキュラム草稿、ありがとうございます！思った以上に良いコンテンツになりそう。

いくつか気になった点についてコメントしてみました。特に JSON::PP を使うのに、標準でエクスポートされる関数を使うか、アローを重ねて Wide character へのアップグレードが発生しないように使うかは、コメント部分にも書きましたが色々要検討かなと思っています。

API 実習で他に良い材料が無い、かつ今までPerl入学式で避け続けてきた日本語処理に踏み込んでもいいのでは…ということになれば、この後にガツンと `use utf8` 的解説を入れることを踏まえて Wide character と正面切って戦うのが良いかなと考えています。もう少し熟慮検討してみましょう。

複数イベントの運営等でレビューが遅れて申し訳ないです。土日は迅速に動けるようにしたい！

2021-11-26 10:04 UTC, xtetsuji commented on text_source/18__http_get.md
> +[HTTP::Tiny - 小さく、シンプルで、正しい HTTP/1.1 クライアント - perldoc.jp](https://perldoc.jp/docs/modules/HTTP-Tiny-0.017/Tiny.pod)
ここのリンク、バージョンによらないパーマリンクがあるので、これに変えましょう！

```suggestion
[HTTP::Tiny - 小さく、シンプルで、正しい HTTP/1.1 クライアント - perldoc.jp](https://perldoc.jp/HTTP::Tiny)
```

2021-11-26 10:04 UTC, xtetsuji commented on text_source/18__http_get.md
> +Perl のモジュールには Perl インストール時に一緒にインストールされる標準モジュールと、インストールが必要な外部モジュールがあります。
もしスライドの余白的に大丈夫であれば、ここもしくはどこかで `HTTP::Tiny` は Perl 5.14 以降ならコアで入っていることを書いておいてもいいかもですね。

2021-11-26 10:04 UTC, xtetsuji commented on text_source/18__http_get.md
> +### Web API の共通言語 JSON
共通言語なのは確かにと思うのですが、プログラミング言語と混同する可能性もあるかなと思って、例えば「共通データ形式」などに言い換えると良いかなと思ったのですが、心配性ですかね。

2021-11-26 10:04 UTC, xtetsuji commented on text_source/18__http_get.md
> +この警告は、プログラムから見て「外部」であるインターネット（今回の Web API 含む）やデータベース、ファイルなどから入手・入力したデータをターミナルに表示しようとした時に発せられることが多いものです。
HTTP::Tiny はレスポンスをバイト列で作りますが、JSON::PP の decode_json が Wide character すなわちマルチバイト文字列にしているっぽいですね。

JSON::PP の decode_json において

```
  decode_json
        $perl_scalar = decode_json $json_text

    The opposite of "encode_json": expects an UTF-8 (binary) string and
    tries to parse that as an UTF-8 encoded JSON text, returning the
    resulting reference. Croaks on error.

    This function call is functionally identical to:

        $perl_scalar = JSON::PP->new->utf8->decode($json_text)
```

と書かれているので、回避策として `decode_json($content)` と書いていた部分を `JSON::PP->new->decode($content)` とする（ `->utf8` を挟まない）と Wide character にはならないかなー。アローがくどいかと思ったりしましたが、HTTP::Tiny も `HTTP::Tiny->new()->get($url)` 的呼び出しをしているのであればいいかなーと思ったり。

ここらで Perl のマルチバイト文字列のことを正面切って解説してもいいのではという気もしてきます。悩み……。

2021-11-26 10:04 UTC, xtetsuji commented on text_source/19__http_post.md
> +GET メソッドは主にインターネットから情報を入手する、表示するために利用されます。それに対し、POST メソッドはインターネットに情報を送信する利用します。
GET も情報を送信していることに変わりないので、もう少し表現工夫したいかも。

- GET : インターネットを介してサーバから情報を入手する
- POST :  インターネットを介してサーバに情報の書き込み等の処理を促す

とかですかね。表現が難しい。うーむ。

2021-11-26 10:04 UTC, xtetsuji commented on text_source/19__http_post.md
> +そういった時は、他の言語での実装やブログ、Qiita などの記事も参考になります。Perl入学式の Discord 掲示板で聞いてみるのも良いでしょう。
掲示板でも通じるかと思いますが、チャンネル（またはテキストチャンネル）にしておきましょう！

```suggestion
そういった時は、他の言語での実装やブログ、Qiita などの記事も参考になります。Perl入学式の Discord チャンネルで聞いてみるのも良いでしょう。
```

2021-11-26 10:04 UTC, xtetsuji commented on text_source/19__http_post.md
> +};
decode_json のところでも解説済みですが、ここもたぶん `encode_json($data)` ではなく `JSON::PP->new()->encode($data)` にすると JSON::PP が Wide character にアップグレードせず（エディタ上では日本語文字列に見える）バイト列をそのまま引き上げて JSON 文字列にするから大丈夫……かな。

実験していないのでなんとも言えないのと、 `encode_json` とアローが続く書き方のどちらが良いかという部分、あと良い機会なのでここらで `use utf8` について解説したほうが良いという部分も含め、ちょっと検討したいですね。

もし余った時間があれば、 `use utf8` を含め、日本語文字列の1文字を正しく1文字と測定するには……と言ったことを解説しても良いかも……。

```perl
my $hello = "こんにちは";
print length($hello); # => 15 ???
```

2021-11-29 12:07 UTC, sironekotoro commented on text_source/18__http_get.md
> +### Web API の共通言語 JSON
まぁ確かに、言語ではないすね。直しておきます。

2021-11-29 12:18 UTC, sironekotoro commented on text_source/19__http_post.md
> +GET メソッドは主にインターネットから情報を入手する、表示するために利用されます。それに対し、POST メソッドはインターネットに情報を送信する利用します。
サーバも含めてインターネットの一部、みたいにするのはちょっと大きな括りすぎたかも。直しておきます。

2021-11-29 12:32 UTC, sironekotoro commented on text_source/18__http_get.md
> +この警告は、プログラムから見て「外部」であるインターネット（今回の Web API 含む）やデータベース、ファイルなどから入手・入力したデータをターミナルに表示しようとした時に発せられることが多いものです。
まぁ、マルチバイト文字列の解説はそれだけで1章いけるので、今回の GET / POST と混ぜるのは厳しいかなぁ。
とりあえず今回は、HTTP::Tiny もいわば「GET関数」みたいな使い方してるんで、JSONもこういうものだ！と脳筋で押し付けて良いかなぁと思います。
まず成功体験積んでもらうってことで。

2021-11-30 04:48 UTC, sironekotoro commented on text_source/18__http_get.md
> +この警告は、プログラムから見て「外部」であるインターネット（今回の Web API 含む）やデータベース、ファイルなどから入手・入力したデータをターミナルに表示しようとした時に発せられることが多いものです。
> JSON::PP->new->decode($content) とする（ ->utf8 を挟まない）と Wide character にはならないかなー

ならなかったです。
ということで、こちらを採用しました

2021-11-30 04:49 UTC, sironekotoro commented on text_source/19__http_post.md
> +};
>JSON::PP->new()->encode($data) にすると JSON::PP が Wide character にアップグレードせず（エディタ上では日本語文字列に見える）バイト列をそのまま引き上げて JSON 文字列にするから大丈夫……かな。

大丈夫でした。おかげで、「とりあえず日本語をPOSTする」というところまではいけました。
JSON::PP は昔 `from_json`, `to_json` てなメソッドがあったんですが、これが encode しないメソッドだったんですかねー

2021-11-30 09:31 UTC, xtetsuji commented on text_source/18__http_get.md
> +この警告は、プログラムから見て「外部」であるインターネット（今回の Web API 含む）やデータベース、ファイルなどから入手・入力したデータをターミナルに表示しようとした時に発せられることが多いものです。
basic の範囲では、文字コードは触れたとしても脳筋でいいかなと思います。 `JSON::PP->new->decode` で Wide character を経ない作戦でいきましょう！

2021-11-30 09:32 UTC, xtetsuji commented on text_source/19__http_post.md
> +};
確かに、 `from_json` `to_json` がそれ系だったっぽいですね。

2021-12-02 11:59 UTC, xtetsuji requested changes
@sironekotoro API解説部分の修正＆日本語処理解説部分の追加、ありがとうございます！

API解説部分はこれで大丈夫そうです。分量的にもっと欲張りたい気もしますが、現地で時間が余りそうでかつノッてきたら、即興で応用問題をやっていきましょうか！

日本語処理解説部分、ついに今まで踏み入れなかった領域に踏み込めそうですね。内容的に間違った記述も無く、概ね大丈夫だと感じました。一部コメントを付けています。

踏み込んで解説したい欲はあるものの、受講生から出てくるであろう最低限の「なぜ」への回答のみ厳選して書いて、その他の疑問点は今後作るであろうアドバンスド版に任せる方向がいいかなと感じました。

2021-12-02 11:59 UTC, xtetsuji commented on text_source/20__perl_and_Japanese.md
> +このため、`length` 関数は 15 文字と文字数を返したのです。
まさにこのからくりによって `length($greet)` が 15 になるのですよね。

バイト列の「バイト」が何かも、もし余裕があればスライド1枚追加して軽く触れておきたいなと思いました（表現難しそうであれば、講義中の雑談でカバーしましょう！）。バイトのことが分かると、1バイトと1文字が同等かそうでないかで理解がはかどりそう。

ポイントとしては以下でしょうか。

- 16進数2桁で表せる数値は、10進数でいう 0〜255 (0x00 〜 0xFF) の 256 (`== 2**8`) 種類であり、256個の異なる値を表すことができる単位が「バイト」
- 英語等の欧米圏の言語やプログラミング言語で使われている英数字や記号は、1バイトつまり 0〜256 ( 0x00〜0xFF ) の範囲で番号付けされている
- つまり英数字や記号は1バイトと1文字が対応しているので、 `length` で意図した文字列が返ってくる
- 日本語の文字全部を 256個の範囲で表現することは明らかに無理で、複数バイト（マルチバイト）で1文字を表す工夫（文字コード、文字エンコーディング）がされている（これ以上深入りすると文字コードの講義になりそうなので雰囲気でごまかしましょう）

2021-12-02 11:59 UTC, xtetsuji commented on text_source/20__perl_and_Japanese.md
> +3. 1, 2 のような処理をした文字列を出力するときは `encode` してテキスト文字列をバイト列（バイナリ文字列）にする。
まさにこれですよね。

といいつつも、 `use utf8` ナシで書いた日本語文字列（実際はバイト列）をそのまま加工すること無く、単なる出力用メッセージとしてあるがまま出力する場合は、このあたりに全く触れなくてもいいのも事実。そして解説する側としては、初学者は要不要の判断ができないとして `use utf8` 励行みたいな書き方をしがちだけど、世の中に出回るコードがそうなっていないという矛盾は感じます（たぶん初学者も）。

これで初学者が分かってくれるかは未知数ですが、たぶん以下を教えるといいのかなと思いました。

- バイト列で書いた日本語文字列を単にすぐ出力するなら `use utf8` で (Wide character な) 文字列にしなくてもよい
- **日本語の1文字が Perl のコード中でも1文字であるという処理をしたい場合 `use utf8` が必須**となる。Perl入学式の範囲ではだいたい以下が全て
    - `length` 関数による文字列長取得
    - 文字列分割の特殊な split 呼び出し `split //, $string`
        - その他の文字列処理関数だと `substr` があるけれど、Perl 入学式では対象外
    - 正規表現で「1文字」を表す `.` や `[●]` あたり
        - `my ($topchar) = "こんにちは" =~ /^(.)/` で「こ」を取るためには `use utf8` が必要
        - その他に正規表現で「1文字」を取る方法はあり、 `use utf8` 等でロケールがマルチバイトであるとすると `\w` も日本語文字1文字にマッチしたはず（だけどPerl入学式では対象外にしましょう）
        - Unicode だと結合文字も考慮した1文字を `.` より厳密に（？）表すための `\X` とかがあったり

このあたり、書くとしてもニュアンスは面倒だなという気もするので、スライドに記載はせず、時間が余って受講生の理解具合も良好な場合には、必要に応じて雑談で補うというのも手かなと思いました。

2021-12-02 11:59 UTC, xtetsuji commented on text_source/20__perl_and_Japanese.md
> +```
コード種別の記載が漏れているかも。

```suggestion
```perl
```

2021-12-02 14:44 UTC, sironekotoro commented on text_source/20__perl_and_Japanese.md
> +このため、`length` 関数は 15 文字と文字数を返したのです。
この辺り、上手くはしょりきれずにスライド追加となってしまいました。自分の理解は深まったので良かったです。

2021-12-02 14:44 UTC, sironekotoro commented on text_source/20__perl_and_Japanese.md
> +3. 1, 2 のような処理をした文字列を出力するときは `encode` してテキスト文字列をバイト列（バイナリ文字列）にする。
このあたり、実例とその後の練習問題も追加してみました。

2021-12-02 15:03 UTC, sironekotoro commented
@xtetsuji なお、今回予定している以下の3つのスライドで、合計60枚になりました。
- 18__http_get.md
- 19__http_post.md
- 20__perl_and_Japanese.md

2021-12-02 15:20 UTC, xtetsuji commented
60枚、進捗に応じて雑談を入れることを加味したら、ちょうど良い枚数かもしれないですね。

コメントを取り入れた修正ありがとうございます。明日再度目を通してみますが、ザッと修正箇所を読んでみた限りは適切な記述で良い感じでした。YAPC のコラムも嬉しいポイント！

2021-12-03 05:03 UTC, xtetsuji requested changes
@sironekotoro 日本語処理部分の修正、ありがとうございます！

軽微な部分ですが、一箇所コメントを入れました。それ以外は大丈夫かと思います。

分量も60ページ少々、前回までの傾向を見ると2時間台でほどよく終わるという感じかなと考えています。今回を足がかりに、新たな第5回をやっていきましょう！

2021-12-03 05:03 UTC, xtetsuji commented on text_source/20__perl_and_Japanese.md
> +if ($input =~ /^(.).+(.)$/){   # バイト列のまま正規表現！
`$input` が2文字の場合も対応していいかなと思うので、量指定子は `+` から `*` にしていいかなと思いました

```suggestion
if ($input =~ /^(.).*(.)$/){   # バイト列のまま正規表現！
```

1文字でも…というところは、スライドに入れず、講義の雰囲気を見て発展問題として必要に応じて入れるでいいかなと思いました。

2021-12-04 01:59 UTC, merged