2022年春第1回スライド
perl-entrance-org/workshop-basic-online pull request #98
Opened 2022-05-15 16:20 UTC by sironekotoro

- 01 〜 05 まで
    - もう少しあった方が良い？
- オンライン版でも環境構築が前提となったため、Wandboxについての説明を削除
- 現時点で70枚
- 将来的なHonKit化を見据えて、h3タグに相当する `###` が一意になるように変更
    - `.`（ドット）, `_`（アンダースコア）, 半角カッコが利用できない模様。 HTMLのアンカーの制限(?)と思われる
- 昨年と同じく、1st/new_slide.md にマージしたものを作成、コメント確認＆修正後に`slide.md`にリネーム予定

2022-05-16 14:42 UTC, xtetsuji requested changes
@sironekotoro 修正ありがとうございます！気づいた部分コメントしてみました。

改めて通しで第1回資料を読んでみて、今回の修正範囲外で気になったところもあったのですが、そちらは別 Pull Request を作ろうかなと考えています。

2022-05-16 14:42 UTC, xtetsuji commented on text_source/01__building_perl_learning_environment.md
>  - コミュニケーション：<a href="https://discord.com/channels/741610576609935430/741610901303721998" target="_blank"><ruby>Discord<rt>ディスコード</rt></ruby></a>
今回の修正範囲ではないのですが、Discord リンクは紹介ページをはさみたいですね。Discord Perl入学式サーバ未参加の人がクリックしたら、唐突にログイン画面が出るのもなぁという。

以前から思って Issue にしていました。

- https://github.com/perl-entrance-org/perl-entrance-org.github.com/issues/77

もしくはサーバ招待URLにして、招待画面のカスタマイズもアリかな……。

2022-05-16 14:42 UTC, xtetsuji commented on text_source/02__terminal_shell.md
> +Windowsの方はインストールした `MSY2 MSYS` を 、 Mac ユーザーの方は Launchpad から「ターミナル」を選択し、起動します。
パッと確認できなかったのですが、 Windows の方の `` `MSY2 MSYS`  `` は typo ？ MSY2 で検索しても何も出てこなかったので……。

2022-05-16 14:42 UTC, xtetsuji commented on text_source/02__terminal_shell.md
> +### rmdir：ディレクトリを削除する
ここに限らず、スライドでのフォントデザインから `## ターミナルとシェル入門` と `###` の heading 2 と 3 を繰り返すようにしたと思うのですが、この heading の使い方をすると後々書籍体裁まわりや目次生成まわりで不都合があるかなと感じました。

とはいえデザインを捨てない解決策もパッと思い浮かばないし、いったんデザイン優先でいいかなと感じています。

ちゃんとやるとすると Markdown だと表現力不足で、

```
<div class="slide_only">ターミナルとシェル入門</div>
```

として、Reveal の CSS で `##` と同じ大きさを当て、かつ書籍目次方向で出力するとき `.slide_only { display: none; }` するとかかなぁと妄想していました……とメモ。

2022-05-16 14:42 UTC, xtetsuji commented on text_source/02__terminal_shell.md
> +`start DIRECTORY` で、`DIRECTORY` を Windows　標準の Explorer というファイルマネージャで開きます。
某執筆で「という」を削除し続けたので気になってしまう……というのは置いといて、手間でなければエクスプローラーはこれだよという画面キャプチャがあるといいかもしれませんね。Windows を使っている初学者は「エクスプローラー」と聞いてもパッと思い浮かばない可能性もあるので。

2022-05-16 14:42 UTC, xtetsuji commented on text_source/02__terminal_shell.md
> +3. **カレントディレクトリ（現在いるディレクトリ）**のパスを `pwd` で表示し、その後に、 `start` もしくは `open` を使って、ファイルマネージャで開いてみましょう。
ジャストアイデアですが、ディレクトリ中で `mkdir` した結果はエクスプローラーや Finder に即時反映されるので、CLI と GUI は同じものを操作している実感を持たせることができるかも。

簡単に解決するとすれば 1 の前に 3 を持ってくることかなと思うのですが、 `mkdir` と `open` の解説順序もあるので、3 の後にさらに `mkdir` や `touch` する課題があるとよさそう？

こちらの修正も任意で大丈夫です。

2022-05-16 14:42 UTC, xtetsuji commented on text_source/Makefile
>  	@echo "  make ../2nd/new_slide.md"
`FILES_DAY1` 追加ありがとうございます。

ついでに `make` 単独で打ったときにヘルプが出てくるよう対応して頂けると！


```suggestion
usage:
	@echo "Usage:"
	@echo "  make ../1st/new_slide.md"
	@echo "  make ../2nd/new_slide.md"
```

2022-05-17 11:17 UTC, sironekotoro commented on text_source/02__terminal_shell.md
> +Windowsの方はインストールした `MSY2 MSYS` を 、 Mac ユーザーの方は Launchpad から「ターミナル」を選択し、起動します。
typoです。直します。あと、他で msys2 だったところを MSYS2 に変更して統一します。

2022-05-17 11:19 UTC, sironekotoro commented on text_source/02__terminal_shell.md
> +### rmdir：ディレクトリを削除する
そうなんすよねー表現力の問題なんですよね・・・

今自分のいるスライドがどの単元か？ってのは別に一番上にh2で表示しなくとも良い・・・むしろスライドのフッター的なとこがあればそこでも良いと思うのですが。

とりあえず、現状維持でタイミング来たら変えます。

2022-05-17 15:17 UTC, sironekotoro commented on text_source/Makefile
>  	@echo "  make ../2nd/new_slide.md"
追加しました！

2022-05-17 15:19 UTC, sironekotoro commented on text_source/02__terminal_shell.md
> +`start DIRECTORY` で、`DIRECTORY` を Windows　標準の Explorer というファイルマネージャで開きます。
せっかくの技術評論社のあれ活かせてませんでしたね・・・そのうち一括で修正したい。

とりあえず、画像を追加しました。
合わせて、画像用のフォルダ`image_source`も追加しました。
順次、画像はこちらのフォルダへリンクを張り替えていくつもりです。

2022-05-17 15:20 UTC, sironekotoro commented on text_source/01__building_perl_learning_environment.md
>  - コミュニケーション：<a href="https://discord.com/channels/741610576609935430/741610901303721998" target="_blank"><ruby>Discord<rt>ディスコード</rt></ruby></a>
こっちは公式ページにページを追加してからですかね。こちらも手をつけないとなぁ。

2022-05-17 15:30 UTC, xtetsuji commented on text_source/02__terminal_shell.md
> +`start DIRECTORY` で、`DIRECTORY` を Windows　標準の Explorer というファイルマネージャで開きます。
画像追加ありがとうございます！

あの良くない表現検出 grep、Perl入学式の資料にも時間あるときに通して、それ専用の修正プルリク作って作業するとかがいいかもですね。

2022-05-18 05:09 UTC, xtetsuji commented
- メモ：5月19日（木曜日）に [in千歳第1回の開講がある](https://perl-entrance-chitose.connpass.com/event/248527/)ので、この Pull Request をマージするのは20日（金曜日）以降にする

2022-05-26 02:49 UTC, xtetsuji approved these changes
現時点での修正で大丈夫そうなので self re-request review して Approve しておきます :+1:

マージに関しても、in千歳側は大きな影響がないので今週任意のタイミングでして良いとのことです。

2022-05-26 05:01 UTC, sironekotoro commented
Makefileにコンフリクトが生じてましたが、GitHub上で編集してマージします。

2022-05-26 05:02 UTC, merged

2022-05-26 05:18 UTC, sironekotoro commented
しまった、ファイルネームのリネーム前にマージしてしまった。

revert怖いんで、別途セルフマージします